import { sql } from "drizzle-orm";
import {
  check,
  integer,
  pgTable,
  text,
  timestamp,
  unique,
  uuid,
} from "drizzle-orm/pg-core";

/**
 * Tenancy base schema (VIT-107, ADR-0003, threat model C2/C8/C9).
 *
 * This file describes columns, constraints and indexes. Row level security,
 * grants, ownership and `resolve_host` are NOT expressible in Drizzle (FORCE RLS,
 * SECURITY DEFINER, role ownership), so they live in the same migration as
 * hand-reviewed SQL: drizzle/migrations/0000_tenancy_base.sql.
 *
 * Conventions: UUID v7 generated by the application (no database default, because
 * gen_random_uuid() is v4; a CHECK rejects any other version), timestamptz in UTC,
 * `version` for optimistic concurrency.
 *
 * CHECK expressions are static `sql` templates (no `sql.raw`, no interpolated
 * strings). The slug and host patterns accept a lowercase DNS label: letters,
 * digits, inner hyphens, 1-63 chars.
 */

/**
 * The tenant root. Its RLS policy compares `id` (there is no `store_id` column).
 */
export const stores = pgTable(
  "stores",
  {
    id: uuid("id").primaryKey(),
    /** Subdomain label, unique; reserved words and renames are enforced by use cases (VIT-121). */
    slug: text("slug").notNull().unique("stores_slug_key"),
    name: text("name").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    version: integer("version").notNull().default(1),
  },
  (t) => [
    check(
      "stores_id_uuid_v7",
      sql`id::text ~ '^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'`,
    ),
    check(
      "stores_slug_format",
      sql`slug ~ '^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$'`,
    ),
    check("stores_name_length", sql`char_length(${t.name}) BETWEEN 1 AND 80`),
    check("stores_version_positive", sql`${t.version} >= 1`),
  ],
);

/**
 * host -> store. The host is stored already normalised (lowercase, no port, no
 * trailing dot, no wildcard, <= 253 chars) and the CHECK refuses anything else, so
 * resolve_host() and the table agree on what a valid host is.
 *
 * `store_id` references the tenant root with a simple FK because `stores` has no
 * `store_id` column to pair with. Every future table that references `domains`
 * must use the composite FK (store_id, id) that `domains_store_id_id_key` enables
 * (ADR-0003 §5, C9).
 */
export const domains = pgTable(
  "domains",
  {
    id: uuid("id").primaryKey(),
    storeId: uuid("store_id")
      .notNull()
      .references(() => stores.id, { onDelete: "restrict" }),
    host: text("host").notNull().unique("domains_host_key"),
    /** NULL until verified. Custom domains stay NULL until their trigger (VITRINIA.md §6.5). */
    verifiedAt: timestamp("verified_at", { withTimezone: true }),
    /**
     * Tombstone for a released host (threat model §8; used by VIT-121). Nullable
     * and without logic in Sprint 1; added now to avoid a Sprint 3 migration.
     */
    releasedAt: timestamp("released_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    version: integer("version").notNull().default(1),
  },
  (t) => [
    // Composite-FK target for future tables (store_id, id).
    unique("domains_store_id_id_key").on(t.storeId, t.id),
    check(
      "domains_id_uuid_v7",
      sql`id::text ~ '^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'`,
    ),
    check(
      "domains_host_format",
      sql`char_length(host) <= 253 AND host ~ '^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?(\\.[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?)*$'`,
    ),
    check("domains_version_positive", sql`${t.version} >= 1`),
  ],
);

export type StoreRow = typeof stores.$inferSelect;
export type NewStoreRow = typeof stores.$inferInsert;
export type DomainRow = typeof domains.$inferSelect;
export type NewDomainRow = typeof domains.$inferInsert;
