import { eq, sql } from "drizzle-orm";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import type { DatabaseHandle } from "@/infra/db/client";
import { bindWithStoreTx, type WithStoreTx } from "@/infra/db/with-store-tx";
import { uuidv7 } from "@/infra/uuid-v7";
import { insertCatalog } from "@/modules/catalog/infrastructure/db-catalog-writer";
import { productVariants } from "@/modules/catalog/infrastructure/schema";
import { KANUWIN_CATALOG } from "@/modules/catalog/infrastructure/seed/kanuwin";
import {
  type NewOrderRow,
  orderContacts,
  orderItems,
  orders,
} from "@/modules/orders/infrastructure/schema";
import {
  expectPgError,
  openAppUser,
  openMigrator,
  type SeededStore,
  seedStore,
  truncateAll,
  unique,
} from "./helpers";

/**
 * Orders tables (VIT-186; threat model orders O2, O9, O10, O11).
 * The generic cross-store checks (RLS, fail-closed, WITH CHECK) are generated by
 * tests/integration/tenant-isolation; this file covers what is specific to orders:
 * composite FKs, immutability for app_user, CHECK arithmetic and the idempotency key.
 */

let app: DatabaseHandle;
let owner: DatabaseHandle;
let withStoreTx: WithStoreTx;
let A: SeededStore;
let B: SeededStore;
let variantOfA: string;
let variantOfB: string;

function order(storeId: string, overrides: Partial<NewOrderRow> = {}) {
  return {
    id: uuidv7(),
    storeId,
    code: `K${Math.random()
      .toString(36)
      .replace(/[^a-z2-9]/g, "")
      .toUpperCase()
      .padEnd(6, "X")
      .slice(0, 7)}`,
    idempotencyKey: uuidv7(),
    requestHash: "a".repeat(64),
    deliveryType: "pickup",
    subtotalClp: 2000,
    shippingClp: 0,
    totalClp: 2000,
    ...overrides,
  } satisfies NewOrderRow;
}

function item(storeId: string, orderId: string, variantId: string | null) {
  return {
    id: uuidv7(),
    storeId,
    orderId,
    variantId,
    position: 0,
    productName: "Producto",
    variantLabel: "1 kg",
    unitPriceClp: 1000,
    quantity: 2,
    lineTotalClp: 2000,
  };
}

async function firstVariant(storeId: SeededStore["id"]): Promise<string> {
  return withStoreTx(storeId, async (tx) => {
    const [row] = await tx
      .select({ id: productVariants.id })
      .from(productVariants);
    if (!row) throw new Error("no variant");
    return row.id;
  });
}

beforeAll(async () => {
  app = openAppUser();
  owner = openMigrator();
  await truncateAll(owner);
  withStoreTx = bindWithStoreTx(app.db);
  A = await seedStore(app, unique("ord-a"));
  B = await seedStore(app, unique("ord-b"));
  await insertCatalog(withStoreTx, A.id, KANUWIN_CATALOG);
  await insertCatalog(withStoreTx, B.id, KANUWIN_CATALOG);
  variantOfA = await firstVariant(A.id);
  variantOfB = await firstVariant(B.id);
});

afterAll(async () => {
  await truncateAll(owner);
  await app.close();
  await owner.close();
});

describe("orders: composite foreign keys (O9)", () => {
  it("accepts an item and a contact of the same store", async () => {
    const o = order(A.id);
    await withStoreTx(A.id, async (tx) => {
      await tx.insert(orders).values(o);
      await tx.insert(orderItems).values(item(A.id, o.id, variantOfA));
      await tx.insert(orderContacts).values({
        id: uuidv7(),
        storeId: A.id,
        orderId: o.id,
        name: "Comprador",
        phone: "+56912345678",
      });
    });
  });

  it("rejects an item whose order belongs to another store", async () => {
    const foreign = order(B.id);
    await withStoreTx(B.id, (tx) => tx.insert(orders).values(foreign));
    await expectPgError(
      withStoreTx(A.id, (tx) =>
        tx.insert(orderItems).values(item(A.id, foreign.id, null)),
      ),
      /foreign key|violates/i,
    );
  });

  it("rejects a contact whose order belongs to another store", async () => {
    const foreign = order(B.id);
    await withStoreTx(B.id, (tx) => tx.insert(orders).values(foreign));
    await expectPgError(
      withStoreTx(A.id, (tx) =>
        tx.insert(orderContacts).values({
          id: uuidv7(),
          storeId: A.id,
          orderId: foreign.id,
          name: "Comprador",
          phone: "+56912345678",
        }),
      ),
      /foreign key|violates/i,
    );
  });

  it("rejects an item that points at a variant of another store", async () => {
    const o = order(A.id);
    await withStoreTx(A.id, (tx) => tx.insert(orders).values(o));
    await expectPgError(
      withStoreTx(A.id, (tx) =>
        tx.insert(orderItems).values(item(A.id, o.id, variantOfB)),
      ),
      /foreign key|violates/i,
    );
  });

  it("allows one contact per order", async () => {
    const o = order(A.id);
    const contact = () => ({
      id: uuidv7(),
      storeId: A.id,
      orderId: o.id,
      name: "Comprador",
      phone: "+56912345678",
    });
    await withStoreTx(A.id, async (tx) => {
      await tx.insert(orders).values(o);
      await tx.insert(orderContacts).values(contact());
    });
    await expectPgError(
      withStoreTx(A.id, (tx) => tx.insert(orderContacts).values(contact())),
      /unique|duplicate/i,
    );
  });

  it("keeps the item snapshot when the seller deletes the variant", async () => {
    const o = order(A.id);
    const line = item(A.id, o.id, null);
    await withStoreTx(A.id, async (tx) => {
      const [fresh] = await tx
        .select({ id: productVariants.id })
        .from(productVariants)
        .offset(3)
        .limit(1);
      await tx.insert(orders).values(o);
      await tx
        .insert(orderItems)
        .values({ ...line, variantId: fresh?.id ?? null });
      if (fresh) {
        await tx
          .delete(productVariants)
          .where(eq(productVariants.id, fresh.id));
      }
    });
    const [saved] = await withStoreTx(A.id, (tx) =>
      tx.select().from(orderItems).where(eq(orderItems.id, line.id)),
    );
    expect(saved?.variantId).toBeNull();
    expect(saved?.storeId).toBe(A.id);
    expect(saved?.productName).toBe("Producto");
  });
});

describe("orders: immutable snapshot for app_user (O10)", () => {
  let o: ReturnType<typeof order>;
  let line: ReturnType<typeof item>;

  beforeAll(async () => {
    o = order(A.id);
    line = item(A.id, o.id, variantOfA);
    await withStoreTx(A.id, async (tx) => {
      await tx.insert(orders).values(o);
      await tx.insert(orderItems).values(line);
    });
  });

  const denied = /permission denied/i;

  it("cannot UPDATE or DELETE order_items", async () => {
    await expectPgError(
      withStoreTx(A.id, (tx) =>
        tx.execute(sql`update order_items set unit_price_clp = 1`),
      ),
      denied,
    );
    await expectPgError(
      withStoreTx(A.id, (tx) => tx.execute(sql`delete from order_items`)),
      denied,
    );
  });

  it("cannot change amounts, items or code of an order", async () => {
    for (const column of [
      "total_clp",
      "subtotal_clp",
      "shipping_clp",
      "code",
      "delivery_type",
      "idempotency_key",
    ]) {
      await expectPgError(
        withStoreTx(A.id, (tx) =>
          tx.execute(
            sql`update orders set ${sql.identifier(column)} = ${sql.identifier(column)}`,
          ),
        ),
        denied,
      );
    }
  });

  it("cannot DELETE orders or order_contacts", async () => {
    await expectPgError(
      withStoreTx(A.id, (tx) => tx.execute(sql`delete from orders`)),
      denied,
    );
    await expectPgError(
      withStoreTx(A.id, (tx) => tx.execute(sql`delete from order_contacts`)),
      denied,
    );
  });

  it("can move the status (confirmation, VIT-127)", async () => {
    await withStoreTx(A.id, (tx) =>
      tx
        .update(orders)
        .set({ status: "confirmed", version: 2, updatedAt: new Date() })
        .where(eq(orders.id, o.id)),
    );
    const [saved] = await withStoreTx(A.id, (tx) =>
      tx.select().from(orders).where(eq(orders.id, o.id)),
    );
    expect(saved?.status).toBe("confirmed");
    expect(saved?.totalClp).toBe(2000);
  });

  it("can anonymise a contact (retention, VIT-188)", async () => {
    const o2 = order(A.id);
    await withStoreTx(A.id, async (tx) => {
      await tx.insert(orders).values(o2);
      await tx.insert(orderContacts).values({
        id: uuidv7(),
        storeId: A.id,
        orderId: o2.id,
        name: "Comprador",
        phone: "+56912345678",
        email: "comprador@ejemplo.cl",
      });
      await tx
        .update(orderContacts)
        .set({ email: null, name: "anon", anonymizedAt: new Date() })
        .where(eq(orderContacts.orderId, o2.id));
    });
  });
});

describe("orders: CHECK constraints (O2)", () => {
  const bad = (overrides: Partial<NewOrderRow>) =>
    expectPgError(
      withStoreTx(A.id, (tx) =>
        tx.insert(orders).values(order(A.id, overrides)),
      ),
      /check constraint/i,
    );

  it("total must equal subtotal + shipping", async () => {
    await bad({ totalClp: 1 });
  });

  it("amounts cannot be negative or beyond the cap", async () => {
    await bad({ subtotalClp: -1, totalClp: -1 });
    await bad({
      subtotalClp: 2_000_000_000_000,
      totalClp: 2_000_000_000_000,
    });
  });

  it("pickup has no zone and delivery needs one", async () => {
    await bad({ deliveryType: "pickup", deliveryZone: "Santiago" });
    await bad({ deliveryType: "delivery", deliveryZone: null });
  });

  it("status, channel and currency are closed lists", async () => {
    await bad({ status: "paid" });
    await bad({ channel: "carrier-pigeon" });
    await bad({ currency: "USD" });
  });

  it("the code is random-looking uppercase without ambiguous digits", async () => {
    await bad({ code: "abc" });
    await bad({ code: "ABC10O" });
  });

  it("item lines: quantity 1..99 and line_total = unit price x quantity", async () => {
    const o = order(A.id);
    await withStoreTx(A.id, (tx) => tx.insert(orders).values(o));
    for (const overrides of [
      { quantity: 0 },
      { quantity: -1 },
      { quantity: 100 },
      { lineTotalClp: 1 },
      { unitPriceClp: -5, lineTotalClp: -10 },
    ]) {
      await expectPgError(
        withStoreTx(A.id, (tx) =>
          tx
            .insert(orderItems)
            .values({ ...item(A.id, o.id, null), ...overrides }),
        ),
        /check constraint/i,
      );
    }
  });

  it("contacts: address and invoice data are all-or-nothing", async () => {
    const o = order(A.id);
    await withStoreTx(A.id, (tx) => tx.insert(orders).values(o));
    for (const extra of [{ street: "Calle 1" }, { rut: "12.345.678-5" }]) {
      await expectPgError(
        withStoreTx(A.id, (tx) =>
          tx.insert(orderContacts).values({
            id: uuidv7(),
            storeId: A.id,
            orderId: o.id,
            name: "Comprador",
            phone: "+56912345678",
            ...extra,
          }),
        ),
        /check constraint/i,
      );
    }
  });
});

describe("orders: idempotency key (O11)", () => {
  it("is unique per store, and the same key may exist in another store", async () => {
    const key = uuidv7();
    await withStoreTx(A.id, (tx) =>
      tx.insert(orders).values(order(A.id, { idempotencyKey: key })),
    );
    await expectPgError(
      withStoreTx(A.id, (tx) =>
        tx.insert(orders).values(order(A.id, { idempotencyKey: key })),
      ),
      /unique|duplicate/i,
    );
    await withStoreTx(B.id, (tx) =>
      tx.insert(orders).values(order(B.id, { idempotencyKey: key })),
    );
  });

  it("ON CONFLICT DO NOTHING lets concurrent identical submits share one row", async () => {
    const key = uuidv7();
    const attempts = await Promise.all(
      Array.from({ length: 10 }, () =>
        withStoreTx(A.id, (tx) =>
          tx
            .insert(orders)
            .values(order(A.id, { idempotencyKey: key }))
            .onConflictDoNothing({
              target: [orders.storeId, orders.idempotencyKey],
            })
            .returning({ id: orders.id }),
        ),
      ),
    );
    expect(attempts.filter((rows) => rows.length === 1)).toHaveLength(1);
    const rows = await withStoreTx(A.id, (tx) =>
      tx.select().from(orders).where(eq(orders.idempotencyKey, key)),
    );
    expect(rows).toHaveLength(1);
  });
});
