import { sql } from "drizzle-orm";
import {
  bigint,
  boolean,
  check,
  foreignKey,
  index,
  integer,
  pgTable,
  text,
  timestamp,
  unique,
  uuid,
} from "drizzle-orm/pg-core";

/**
 * Orders schema (VIT-186, ADR-0005, threat model orders O2, O8, O9, O10, O22).
 *
 * Three tables, all tenant tables reached through `withStoreTx`:
 * - `orders`: the snapshot header (totals, delivery option, channel, status). No personal data.
 * - `order_items`: the snapshot lines (name and price at purchase). Immutable for `app_user`.
 * - `order_contacts`: the buyer's data, apart so it can be anonymised at 24 months (ADR-0010).
 *
 * RLS, grants (column-level on `orders`), the FKs to `stores` and to
 * `product_variants` live in drizzle/migrations/0002_orders_tables.sql: Drizzle cannot express
 * them, and `stores`/`product_variants` belong to other modules' schemas.
 *
 * Money is an integer in CLP (`bigint` for sums: 50 lines x 99 x 100 M CLP does not fit in int4).
 * The CHECKs repeat the arithmetic of the use case so a bad write fails in the database too.
 */

export const ORDER_STATUSES = ["intent", "confirmed", "cancelled"] as const;
export const ORDER_CHANNELS = ["whatsapp", "payment_link"] as const;
export const ORDER_DELIVERY_TYPES = ["delivery", "pickup"] as const;

export const orders = pgTable(
  "orders",
  {
    id: uuid("id").primaryKey(),
    storeId: uuid("store_id").notNull(),
    /** Short public code the buyer quotes to the seller. Random, never sequential (O18). */
    code: text("code").notNull(),
    /** Generated by the browser when the checkout opens (O11). */
    idempotencyKey: uuid("idempotency_key").notNull(),
    /** SHA-256 hex of lines + delivery option: same key, other cart => conflict. */
    requestHash: text("request_hash").notNull(),
    status: text("status").notNull().default("intent"),
    channel: text("channel").notNull().default("whatsapp"),
    deliveryType: text("delivery_type").notNull(),
    /** Name of the Store Config zone at purchase time. Null for pickup. */
    deliveryZone: text("delivery_zone"),
    invoice: boolean("invoice").notNull().default(false),
    currency: text("currency").notNull().default("CLP"),
    subtotalClp: bigint("subtotal_clp", { mode: "number" }).notNull(),
    shippingClp: bigint("shipping_clp", { mode: "number" }).notNull(),
    totalClp: bigint("total_clp", { mode: "number" }).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    version: integer("version").notNull().default(1),
  },
  (t) => [
    unique("orders_store_id_id_key").on(t.storeId, t.id),
    unique("orders_store_id_idempotency_key_key").on(
      t.storeId,
      t.idempotencyKey,
    ),
    unique("orders_store_id_code_key").on(t.storeId, t.code),
    index("orders_store_created_idx").on(t.storeId, t.createdAt),
    check(
      "orders_id_uuid_v7",
      sql`id::text ~ '^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'`,
    ),
    check("orders_code_format", sql`${t.code} ~ '^[A-Z2-9]{6,12}$'`),
    check(
      "orders_request_hash_format",
      sql`${t.requestHash} ~ '^[0-9a-f]{64}$'`,
    ),
    check(
      "orders_status_valid",
      sql`${t.status} IN ('intent', 'confirmed', 'cancelled')`,
    ),
    check(
      "orders_channel_valid",
      sql`${t.channel} IN ('whatsapp', 'payment_link')`,
    ),
    check(
      "orders_delivery_type_valid",
      sql`${t.deliveryType} IN ('delivery', 'pickup')`,
    ),
    check(
      "orders_delivery_zone_coherent",
      sql`(${t.deliveryType} = 'delivery' AND ${t.deliveryZone} IS NOT NULL AND char_length(${t.deliveryZone}) BETWEEN 1 AND 60)
        OR (${t.deliveryType} = 'pickup' AND ${t.deliveryZone} IS NULL)`,
    ),
    check("orders_currency_clp", sql`${t.currency} = 'CLP'`),
    check(
      "orders_amounts_range",
      sql`${t.subtotalClp} BETWEEN 0 AND 1000000000000
        AND ${t.shippingClp} BETWEEN 0 AND 1000000000000
        AND ${t.totalClp} BETWEEN 0 AND 1000000000000`,
    ),
    check(
      "orders_total_is_subtotal_plus_shipping",
      sql`${t.totalClp} = ${t.subtotalClp} + ${t.shippingClp}`,
    ),
    check("orders_version_positive", sql`${t.version} >= 1`),
  ],
);

export const orderItems = pgTable(
  "order_items",
  {
    id: uuid("id").primaryKey(),
    storeId: uuid("store_id").notNull(),
    orderId: uuid("order_id").notNull(),
    /** Null once the seller deletes the variant; the snapshot below keeps the order readable. */
    variantId: uuid("variant_id"),
    position: integer("position").notNull(),
    productName: text("product_name").notNull(),
    variantLabel: text("variant_label").notNull(),
    unitPriceClp: integer("unit_price_clp").notNull(),
    quantity: integer("quantity").notNull(),
    lineTotalClp: bigint("line_total_clp", { mode: "number" }).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    unique("order_items_store_id_id_key").on(t.storeId, t.id),
    unique("order_items_store_order_position_key").on(
      t.storeId,
      t.orderId,
      t.position,
    ),
    foreignKey({
      name: "order_items_order_fk",
      columns: [t.storeId, t.orderId],
      foreignColumns: [orders.storeId, orders.id],
    }).onDelete("cascade"),
    check(
      "order_items_id_uuid_v7",
      sql`id::text ~ '^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'`,
    ),
    check("order_items_position_range", sql`${t.position} BETWEEN 0 AND 49`),
    check(
      "order_items_product_name_length",
      sql`char_length(${t.productName}) BETWEEN 1 AND 120`,
    ),
    check(
      "order_items_variant_label_length",
      sql`char_length(${t.variantLabel}) BETWEEN 1 AND 40`,
    ),
    check(
      "order_items_unit_price_range",
      sql`${t.unitPriceClp} BETWEEN 0 AND 100000000`,
    ),
    check("order_items_quantity_range", sql`${t.quantity} BETWEEN 1 AND 99`),
    check(
      "order_items_line_total",
      sql`${t.lineTotalClp} = ${t.unitPriceClp}::bigint * ${t.quantity}`,
    ),
  ],
);

/**
 * Buyer data. Every column except `name` and `phone` is optional and depends on the option the
 * buyer chose (ADR-0005 §5). `anonymized_at` is set by the retention job (VIT-188), which also
 * blanks the PII columns (including RUT, razón social and giro).
 */
export const orderContacts = pgTable(
  "order_contacts",
  {
    id: uuid("id").primaryKey(),
    storeId: uuid("store_id").notNull(),
    orderId: uuid("order_id").notNull(),
    name: text("name").notNull(),
    phone: text("phone").notNull(),
    email: text("email"),
    note: text("note"),
    region: text("region"),
    commune: text("commune"),
    street: text("street"),
    addressExtra: text("address_extra"),
    rut: text("rut"),
    businessName: text("business_name"),
    businessActivity: text("business_activity"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    anonymizedAt: timestamp("anonymized_at", { withTimezone: true }),
    version: integer("version").notNull().default(1),
  },
  (t) => [
    unique("order_contacts_store_id_id_key").on(t.storeId, t.id),
    unique("order_contacts_store_order_key").on(t.storeId, t.orderId),
    foreignKey({
      name: "order_contacts_order_fk",
      columns: [t.storeId, t.orderId],
      foreignColumns: [orders.storeId, orders.id],
    }).onDelete("cascade"),
    check(
      "order_contacts_id_uuid_v7",
      sql`id::text ~ '^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'`,
    ),
    check(
      "order_contacts_name_length",
      sql`char_length(${t.name}) BETWEEN 1 AND 80`,
    ),
    check(
      "order_contacts_phone_length",
      sql`char_length(${t.phone}) BETWEEN 1 AND 20`,
    ),
    check(
      "order_contacts_email_length",
      sql`char_length(${t.email}) BETWEEN 3 AND 254`,
    ),
    check(
      "order_contacts_note_length",
      sql`char_length(${t.note}) BETWEEN 1 AND 500`,
    ),
    check(
      "order_contacts_region_length",
      sql`char_length(${t.region}) BETWEEN 1 AND 80`,
    ),
    check(
      "order_contacts_commune_length",
      sql`char_length(${t.commune}) BETWEEN 1 AND 80`,
    ),
    check(
      "order_contacts_street_length",
      sql`char_length(${t.street}) BETWEEN 1 AND 120`,
    ),
    check(
      "order_contacts_address_extra_length",
      sql`char_length(${t.addressExtra}) BETWEEN 1 AND 120`,
    ),
    check(
      "order_contacts_rut_length",
      sql`char_length(${t.rut}) BETWEEN 3 AND 12`,
    ),
    check(
      "order_contacts_business_name_length",
      sql`char_length(${t.businessName}) BETWEEN 1 AND 120`,
    ),
    check(
      "order_contacts_business_activity_length",
      sql`char_length(${t.businessActivity}) BETWEEN 1 AND 80`,
    ),
    // The address is all or nothing; so is the invoice data.
    check(
      "order_contacts_address_complete",
      sql`(${t.region} IS NULL AND ${t.commune} IS NULL AND ${t.street} IS NULL AND ${t.addressExtra} IS NULL)
        OR (${t.region} IS NOT NULL AND ${t.commune} IS NOT NULL AND ${t.street} IS NOT NULL)`,
    ),
    check(
      "order_contacts_invoice_complete",
      sql`(${t.rut} IS NULL AND ${t.businessName} IS NULL AND ${t.businessActivity} IS NULL)
        OR (${t.rut} IS NOT NULL AND ${t.businessName} IS NOT NULL AND ${t.businessActivity} IS NOT NULL)`,
    ),
    check("order_contacts_version_positive", sql`${t.version} >= 1`),
  ],
);

export type OrderRow = typeof orders.$inferSelect;
export type NewOrderRow = typeof orders.$inferInsert;
export type OrderItemRow = typeof orderItems.$inferSelect;
export type NewOrderItemRow = typeof orderItems.$inferInsert;
export type OrderContactRow = typeof orderContacts.$inferSelect;
export type NewOrderContactRow = typeof orderContacts.$inferInsert;
