import type { Catalog } from "../../application";
import { KANUWIN_DEMO_STORE_ID } from "./kanuwin";

/**
 * SQL that loads a catalog into the local demo database (VIT-186): the Kanuwiñ storefront
 * reads Postgres now, and orders need real variant ids. Ids are fixed (derived from the
 * position in the seed) so the cart in a browser survives a re-seed. Idempotent
 * (`ON CONFLICT DO NOTHING`). It runs as app_user with the tenant set, like infra/seed/demo.sql;
 * a test keeps infra/seed/demo-catalog.sql in sync with this generator.
 */
const q = (value: string) => `'${value.replaceAll("'", "''")}'`;
const nullable = (value: string | undefined | null) =>
  value === undefined || value === null ? "NULL" : q(value);
const num = (value: number | undefined) =>
  value === undefined ? "NULL" : String(value);

function fixedId(kind: "c001" | "c002" | "c003", n: number): string {
  return `0199d0a0-0000-7000-8000-0000${kind}${n.toString(16).padStart(4, "0")}`;
}

export function demoCatalogSql(catalog: Catalog): string {
  const store = KANUWIN_DEMO_STORE_ID;
  const categoryIds = new Map(
    catalog.categories.map((c, i) => [c.id, fixedId("c001", i + 1)]),
  );
  const out: string[] = [
    "-- GENERATED by src/modules/catalog/infrastructure/seed/demo-sql.ts. Do not edit by hand:",
    "--   pnpm demo-catalog:sql   (rewrites this file; a test fails when it is out of date)",
    "-- Kanuwiñ demo catalog for the local database (VIT-186). Runs as app_user, idempotent.",
    "-- Prices and texts come from seed/kanuwin.json (provisional demo data, see seed/README.md).",
    "\\set ON_ERROR_STOP on",
    "",
    "BEGIN;",
    "",
    `SELECT set_config('app.store_id', '${store}', true) AS tenant \\gset`,
    "",
  ];
  for (const c of catalog.categories) {
    out.push(
      `INSERT INTO categories (id, store_id, name, position) VALUES (${q(categoryIds.get(c.id) ?? "")}, '${store}', ${q(c.name)}, ${c.position}) ON CONFLICT (id) DO NOTHING;`,
    );
  }
  out.push("");
  for (const [pi, p] of catalog.products.entries()) {
    const categoryId = categoryIds.get(p.categoryId);
    if (!categoryId)
      throw new Error(`product ${p.slug} has an unknown category`);
    const productId = fixedId("c002", pi + 1);
    const highlights = p.highlights.length
      ? `ARRAY[${p.highlights.map(q).join(", ")}]::text[]`
      : "'{}'::text[]";
    const nutrition = q(
      JSON.stringify(
        p.nutrition.map((n) => ({ label: n.label, value: n.value })),
      ),
    );
    out.push(
      `INSERT INTO products (id, store_id, category_id, slug, name, position, featured, published, short_description, badge, audience, highlights, nutrition_per, nutrition, image_src, image_alt, image_width, image_height, image_provisional) VALUES (${q(productId)}, '${store}', ${q(categoryId)}, ${q(p.slug)}, ${q(p.name)}, ${p.position}, ${p.featured}, true, ${q(p.shortDescription)}, ${nullable(p.badge)}, ${nullable(p.audience)}, ${highlights}, ${nullable(p.nutritionPer)}, ${nutrition}::jsonb, ${nullable(p.image?.src)}, ${nullable(p.image?.alt)}, ${num(p.image?.width)}, ${num(p.image?.height)}, ${p.image?.provisional ?? false}) ON CONFLICT (id) DO NOTHING;`,
    );
    for (const [vi, v] of p.variants.entries()) {
      out.push(
        `INSERT INTO product_variants (id, store_id, product_id, label, price_clp, position) VALUES (${q(fixedId("c003", pi * 10 + vi + 1))}, '${store}', ${q(productId)}, ${q(v.label)}, ${v.price.amount}, ${vi}) ON CONFLICT (id) DO NOTHING;`,
      );
    }
  }
  out.push("", "COMMIT;", "");
  return out.join("\n");
}
