import type { StoreConfig } from "@/modules/store-config/application";
import { KANUWIN_DEMO_STORE_ID } from "./kanuwin";

/**
 * SQL that loads the Kanuwiñ Store Config into the local demo database (VIT-191).
 * Same contract as `demo-sql.ts`: runs as app_user with the tenant set, fixed ids,
 * idempotent (re-running with the same config changes nothing; a changed config
 * overwrites revision 1 and bumps `version`). A test keeps
 * infra/seed/demo-config.sql in sync with this generator.
 */
const q = (value: string) => `'${value.replaceAll("'", "''")}'`;

export const KANUWIN_CONFIG_ROW_ID = "0199d0a0-0000-7000-8000-0000c0040001";

export function demoConfigSql(config: StoreConfig): string {
  const store = KANUWIN_DEMO_STORE_ID;
  const json = q(JSON.stringify(config));
  return [
    "-- GENERATED by src/modules/catalog/infrastructure/seed/demo-config-sql.ts. Do not edit by hand:",
    "--   pnpm demo-config:sql   (rewrites this file; a test fails when it is out of date)",
    "-- Kanuwiñ demo Store Config for the local database (VIT-191). Runs as app_user, idempotent.",
    "-- The content comes from seed/kanuwin-config.ts (preset aves + provisional demo data).",
    "\\set ON_ERROR_STOP on",
    "",
    "BEGIN;",
    "",
    `SELECT set_config('app.store_id', '${store}', true) AS tenant \\gset`,
    "",
    "INSERT INTO store_configs (id, store_id, revision, schema_version, config)",
    `VALUES (${q(KANUWIN_CONFIG_ROW_ID)}, '${store}', 1, ${config.schemaVersion}, ${json}::jsonb)`,
    "ON CONFLICT (store_id, revision) DO UPDATE",
    "  SET config = EXCLUDED.config,",
    "      schema_version = EXCLUDED.schema_version,",
    "      updated_at = now(),",
    "      version = store_configs.version + 1",
    "  WHERE store_configs.config IS DISTINCT FROM EXCLUDED.config;",
    "",
    "COMMIT;",
    "",
  ].join("\n");
}
