import {
  AVES_PRESET,
  parseStoreConfig,
  type StoreConfig,
  type StoreConfigValidator,
} from "@/modules/store-config/application";
import {
  KANUWIN_DELIVERY,
  KANUWIN_HOW_TO_ORDER,
  KANUWIN_WHATSAPP,
} from "./kanuwin";

/**
 * Store Config of the Kanuwiñ demo store (VIT-182): preset `aves` with the store's
 * name, public order number and how-to-order text. It is the SOURCE of the local
 * seed (`infra/seed/demo-config.sql`, generated by `demo-config-sql.ts`); the
 * storefront reads it from Postgres (VIT-191). Validated here so a bad edit fails
 * in the generator test, not on a buyer's phone. The validator is injected because
 * a module may not import another module's infrastructure (ADR-0008).
 */
export function buildKanuwinDemoConfig(
  validator: StoreConfigValidator,
): StoreConfig {
  const sections = AVES_PRESET.pages.home.sections.map((section) =>
    section.type === "text" && section.props.body.includes("REEMPLAZAR:")
      ? { ...section, props: { ...section.props, body: KANUWIN_HOW_TO_ORDER } }
      : section,
  );
  const parsed = parseStoreConfig(
    {
      ...AVES_PRESET,
      identity: { ...AVES_PRESET.identity, name: "Kanuwiñ" },
      contact: { whatsapp: KANUWIN_WHATSAPP },
      // Provisional demo terms (see seed/README.md). Payment links are not set until the
      // seller loads real ones from the portal; the transfer text only tells how to pay.
      checkout: {
        paymentMethods: [
          {
            type: "bank-transfer",
            details:
              "Los datos de la transferencia te los enviamos por WhatsApp al confirmar tu pedido.",
          },
        ],
        delivery: {
          zones: KANUWIN_DELIVERY.zones,
          freeShippingFromClp: KANUWIN_DELIVERY.freeShippingFromClp,
        },
        invoice: false,
      },
      pages: { home: { sections } },
    },
    validator,
  );
  if (!parsed.ok) throw new Error("Kanuwiñ demo Store Config is invalid");
  return parsed.value;
}
