/**
 * Slugs no store can claim as `<slug>.vitrinia.cl` (ADR-0004 §8).
 *
 * Owner: Architect. Adding a word is a normal PR; removing one needs a note in
 * the module doc because a store could then take it. The list is matched after
 * normalisation (`normalizeSlug`), so every entry must itself be a canonical
 * slug (lowercase, `[a-z0-9-]`).
 *
 * Groups: platform hosts, auth and infrastructure, trademarks and payment
 * providers (impersonation), and offensive words in es-CL.
 */

const PLATFORM = [
  "www",
  "app",
  "api",
  "admin",
  "mail",
  "mcp",
  "status",
  "cdn",
  "assets",
  "static",
  "media",
  "img",
  "images",
  "files",
  "docs",
  "help",
  "support",
  "soporte",
  "ayuda",
  "blog",
  "dev",
  "staging",
  "test",
  "demo",
  "preview",
  "portal",
  "panel",
  "dashboard",
  "vitrinia",
  "vitrina",
  "tienda",
  "shop",
  "store",
] as const;

const AUTH_AND_INFRA = [
  "auth",
  "login",
  "logout",
  "signup",
  "register",
  "registro",
  "account",
  "cuenta",
  "oauth",
  "sso",
  "secure",
  "security",
  "ssl",
  "vpn",
  "ns1",
  "ns2",
  "mx",
  "smtp",
  "imap",
  "pop",
  "ftp",
  "ssh",
  "git",
  "webhook",
  "webhooks",
  "localhost",
  "root",
  "system",
  "sistema",
  "autodiscover",
  "autoconfig",
  "mta-sts",
] as const;

const BRANDS_AND_PAYMENTS = [
  "instagram",
  "facebook",
  "meta",
  "whatsapp",
  "tiktok",
  "google",
  "apple",
  "microsoft",
  "amazon",
  "mercadopago",
  "mercado-pago",
  "mercadolibre",
  "mercado-libre",
  "webpay",
  "transbank",
  "khipu",
  "flow",
  "fintoc",
  "kushki",
  "paypal",
  "stripe",
  "banco",
  "bancoestado",
  "banco-estado",
  "bancochile",
  "banco-chile",
  "santander",
  "bci",
  "itau",
  "scotiabank",
  "falabella",
  "ripley",
  "paris",
  "cencosud",
  "lider",
  "sii",
  "gobierno",
  "gob",
  "chileatiende",
  "registro-civil",
  "servipag",
  "cuentarut",
  "cuenta-rut",
  "pago",
  "pagos",
  "pagar",
  "cobro",
  "cobros",
  "payment",
  "payments",
  "checkout",
] as const;

const OFFENSIVE = [
  "mierda",
  "puta",
  "puto",
  "putas",
  "putos",
  "culiao",
  "culia",
  "culiado",
  "culiada",
  "conchetumare",
  "conchatumadre",
  "ctm",
  "maraca",
  "maraco",
  "weon",
  "weona",
  "huevon",
  "huevona",
  "hueon",
  "hueona",
  "pico",
  "pene",
  "porno",
  "porn",
  "sexo",
  "sex",
  "xxx",
  "nazi",
  "hitler",
  "fuck",
  "shit",
] as const;

export const RESERVED_SLUGS: ReadonlySet<string> = new Set<string>([
  ...PLATFORM,
  ...AUTH_AND_INFRA,
  ...BRANDS_AND_PAYMENTS,
  ...OFFENSIVE,
]);

export function isReservedSlug(slug: string): boolean {
  return RESERVED_SLUGS.has(slug);
}
